@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LANDSCAPE()

title Context Diagram for a Social Network System

Person(user, "User", "")
System(system, "Social Network System", "Allows users to create an account, write posts, view posts & statistics, leave comments.")

Rel(user, system, "Uses")

@enduml
