@startuml

skinparam linetype ortho

entity "User" as e01 {
  *user_id : unique number
  --
  *name : text
}

entity "Creates" as e02 {
}

entity "Views" as e06 {
}

entity "Post" as e03 {
  *post_id : unique number
  --
  *author_id : number
  *time_created : number
}

entity "Comment" as e05 {
  *comment_id : unique number
  --
  *author_id : number
  *post_id : number
  parent_comment_id : number
  *time_created : number
}

entity "Posts & comments statistics" as e07 {
  *user_id : number
  *time_generated : number
}

e01 }o..o{ e02
e02 ||--|| e03
e01 }o..o{ e02
e02 ||--|| e05
e01 }|..o{ e06
e06 ||--o{ e03
e06 ||--o{ e05
e06 ||--|| e07

@enduml