@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!includeurl <cloudinsight/kafka>

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/go.puml
!includeurl ICONURL/devicons2/postgresql.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LANDSCAPE()

title Container Diagram for a Toy Social Network System

Person(user, "User")
Container(frontend, "Frontend")

System_Boundary(message_processing_system, "Toy Social") {
    Container(gateway, "Gateway service", "Go", "", "go")
    Container(posts, "Posts service", "Go", "", "go")
    Container(statistics, "Statistics service", "Go", "Aggregates statistics (likes and views) for users' posts", "go")
    
    ContainerDb(gateway_db, "Users data", "PostgreSQL", "", "postgresql")
    ContainerDb(posts_db, "Posts data", "PostgreSQL", "", "postgresql")
    ContainerDb(stat_db, "Statistics data", "Clickhouse", "")
    
    SystemQueue(response_queue, "Apache Kafka", "", "kafka")

    Rel(posts, posts_db, "Reads & writes", "")
    Rel_U(gateway, gateway_db, "Reads & writes", "")
    Rel(statistics, stat_db, "Reads & writes", "")

    Rel(gateway, response_queue, "Produces", "Apache Kafka")
    Rel(response_queue, stat_db, "Consumes", "Apache Kafka")

    Rel(frontend, gateway, "Requests", "REST API")
    Rel(gateway, posts, "", "gRPC")
    Rel(gateway, statistics, "", "gRPC")
}

Rel(user, frontend, "Requests")
@enduml