port: "8000"

kafka:
    topic: "statistics"
    group_name: "statistics"

db:
    username: "postgres"
    host: "host.docker.internal"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"
