name: End-to-end tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Run end-to-end tests
      run: make test-e2e
    
    - name: Show gateway service logs
      if: always()
      run: docker compose logs --no-log-prefix gateway

    - name: Show posts service logs
      if: always()
      run: docker compose logs --no-log-prefix posts

    - name: Show statistics service logs
      if: always()
      run: docker compose logs --no-log-prefix statistics

    - name: Stop containers
      if: always()
      run: make stop
