name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      # https://github.com/golangci/golangci-lint-action/issues/271#issuecomment-1962834476
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --help
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          only-new-issues: true

      - name: Run linter
        run: make lint