name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      
    - name: Run gateway unit tests
      run: |
        cd 'src/gateway'
        go mod download
        go test ./... -v
        cd - > /dev/null

    - name: Run posts unit tests
      run: |
        cd 'src/posts'
        go mod download
        go test ./... -v
        cd - > /dev/null
  
    - name: Run statistics unit tests
      run: |
        cd 'src/statistics'
        go mod download
        go test ./... -v
        cd - > /dev/null
